before_script:
  - "bundle exec rake refinery:testing:dummy_app > /dev/null"
script: "bundle exec rake spec"
notifications:
  email:
    - agustinvinao@gmail.com
env:
  - DB=postgresql
  - DB=mysql
matrix:
  allow_failures:
    - rvm: rbx-19mode
rvm:
  - 1.9.2
  - 1.9.3